class Commands:
	COMMAND_RESET           = 0x01
	COMMAND_PING            = 0x02
	COMMAND_ADD_ACTION      = 0x03
	COMMAND_ADD_EVENT       = 0x04
	COMMAND_ADD_PROPERTY    = 0x05
	COMMAND_REMOVE_ACTION   = 0x06
	COMMAND_REMOVE_EVENT    = 0x07
	COMMAND_REMOVE_PROPERTY = 0x08
	COMMAND_RAISE_EVENT     = 0x09
	COMMAND_CALL_ACTION     = 0x0a
	COMMAND_SET_PROPERTY    = 0x0b
	COMMAND_GET_PROPERTY    = 0x0c
