env = Environment(tools=["default", "arduino"])
env.ConfigureBoard("atmega328")
core = env.ArduinoCore()

env.Append(CCFLAGS="-DENET_CONN")

spi_lib = env.ArduinoLibrary("SPI")
ethernet_lib = env.ArduinoLibrary("Ethernet")
shetsource_lib = env.ArduinoLibrary("shetsource", "../lib")

client_example = env.Sketch("client_example", ["client_example.cpp", shetsource_lib, ethernet_lib, spi_lib, core])
env.Upload(client_example)
